version: "3.9"

services:

# #todo remove unused services and their build contexts

# #todo recommended section for project

  nginx:
    depends_on:
      - php82-fpm
    image: nginx:1
    ports:
      - 80:80
    volumes:
      - ..:/app
      - ../logs:/var/log/nginx
      - ./nginx/app.mmm.conf:/etc/nginx/conf.d/app.mmm.conf
    working_dir: /app

  php82-fpm:
    build: ./php82-fpm/
    volumes:
      - ..:/app
      - ../logs:/var/log/xdebug
    working_dir: /app

# #todo recommended section for library

  php80-cli:
    image: php:8.0-cli
    volumes:
      - ..:/app/
    working_dir: /app

  php81-cli:
    image: php:8.1-cli
    volumes:
      - ..:/app/
    working_dir: /app

  php82-cli:
    build: ./php82-cli/
    volumes:
      - ..:/app
      - ../logs:/var/log/xdebug
    working_dir: /app
