version: "3.9"

services:

# adapt project only

  nginx:
    depends_on:
      - php80-fpm
    image: nginx:1
    ports:
      - 80:80
    volumes:
      - ..:/app
      - ../logs:/var/log/nginx
      - ./nginx/app.mmm.conf:/etc/nginx/conf.d/app.mmm.conf
    working_dir: /app

  php80-fpm:
    build: ./php80-fpm/
    volumes:
      - ../logs:/var/log/xdebug
      - ..:/app
    working_dir: /app

# adapt library only

  php74-cli:
    image: php:7.4-cli
    volumes:
      - ..:/app/
    working_dir: /app

  php80-cli:
    build: ./php80-cli/
    volumes:
      - ..:/app/
    working_dir: /app

  php81-cli:
    image: php:8.1-rc-cli
    volumes:
      - ..:/app/
    working_dir: /app
