version: "3.9"

services:

# #todo remove this section in library

  nginx:
    depends_on:
      - php81-fpm
    image: nginx:1
    ports:
      - 80:80
    volumes:
      - ..:/app
      - ../logs:/var/log/nginx
      - ./nginx/app.mmm.conf:/etc/nginx/conf.d/app.mmm.conf
    working_dir: /app

  php81-fpm:
    build: ./php81-fpm/
    volumes:
      - ../logs:/var/log/xdebug
      - ..:/app
    working_dir: /app

# #todo remove this section in project

  php74-cli:
    image: php:7.4-cli
    volumes:
      - ..:/app/
    working_dir: /app

  php80-cli:
    image: php:8.0-cli
    volumes:
      - ..:/app/
    working_dir: /app

  php81-cli:
    build: ./php81-cli/
    volumes:
      - ..:/app/
    working_dir: /app
