version: "3.9"

services:

  php74:
    image: php:7.4-cli
    volumes:
      - ..:/app/
    working_dir: /app

  php80:
    build: ./php80/
    volumes:
      - ..:/app/
    working_dir: /app

  php81:
    image: php:8.1-rc-cli
    volumes:
      - ..:/app/
    working_dir: /app
