name: "Dependabot Automerge - Action"

on:
  workflow_run:
    workflows: ["Check"]
    types:
      - completed

jobs:
  worker:
    runs-on: ubuntu-latest

#    if: github.actor == 'dependabot[bot]'
    steps:
      - name: automerge
        uses: actions/github-script@v5
        with:
          script: |
            octokit.rest.pulls.createReview({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            })
            octokit.rest.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number
            })
          github-token: ${{ secrets.DEPENDABOT || github.token }}
