name: Build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  fixer:
    name: PHP-CS-Fixer coding standards

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install the composer dependencies
        uses: php-actions/composer@v1

      - name: Check the coding standards
        run: vendor/bin/php-cs-fixer fix --dry-run -v

  phpstan:
    name: PHPStan static analysis

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install the composer dependencies
        uses: php-actions/composer@v1

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

  psalm:
    name: Psalm static analysis

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install the composer dependencies
        uses: php-actions/composer@v1

      - name: Run static analysis
        run: vendor/bin/psalm --show-info=true --shepherd

  unit:
    name: PHPUnit unit tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version:
          - 7.4

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install the composer dependencies
        uses: php-actions/composer@v1

      - name: Run the unit tests
        run: vendor/bin/phpunit
